/* ============================================================================
 * AzamiOS Userspace — Word Expansion (wordexp.h)
 * File: userland/libc/include/wordexp.h
 * ============================================================================ */
#pragma once

#include <stddef.h>

typedef struct {
    size_t we_wordc;   /* Count of words matched */
    char **we_wordv;   /* Pointer to list of expanded words */
    size_t we_offs;    /* Slots to reserve at the beginning of we_wordv */
} wordexp_t;

/* Flags for wordexp() */
#define WRDE_APPEND   (1 << 0)  /* Append words to those generated by previous call */
#define WRDE_DOOFFS   (1 << 1)  /* Number of null pointers to prepend */
#define WRDE_NOCMD    (1 << 2)  /* Fail if command substitution is attempted */
#define WRDE_REUSE    (1 << 3)  /* The pwordexp argument was passed to a previous call */
#define WRDE_SHOWERR  (1 << 4)  /* Do not redirect stderr to /dev/null */
#define WRDE_UNDEF    (1 << 5)  /* Error on undefined shell variables */

/* Error return codes for wordexp() */
#define WRDE_BADCHAR  1  /* Unquoted bad character encountered */
#define WRDE_BADVAL   2  /* Reference to undefined shell variable */
#define WRDE_CMDSUB   3  /* Command substitution requested with WRDE_NOCMD */
#define WRDE_NOSPACE  4  /* Out of memory */
#define WRDE_SYNTAX   5  /* Shell syntax error */

int  wordexp(const char *words, wordexp_t *pwordexp, int flags);
void wordfree(wordexp_t *pwordexp);
