#!/usr/bin/env python3
# =============================================================================
# AzamiOS — System Call Table Generator
# File: scripts/gensyscalltbl.py
#
# Generates kernel/syscall/syscall_table.h from kernel/syscall/syscalls.tbl.
# =============================================================================
import sys
import os
import argparse

TABLE_SIZE = 560

def main():
    parser = argparse.ArgumentParser(description="Generate syscall table header from .tbl file")
    parser.add_argument("--in", dest="tbl_path", default="kernel/syscall/syscalls.tbl", help="Path to syscalls.tbl")
    parser.add_argument("--out", dest="out_path", default="kernel/syscall/syscall_table.h", help="Path to output header")
    args = parser.parse_args()

    if not os.path.exists(args.tbl_path):
        sys.stderr.write(f"Error: {args.tbl_path} not found\n")
        sys.exit(1)

    entries = []
    seen_nrs = {}
    with open(args.tbl_path, "r") as f:
        for line_num, line in enumerate(f, 1):
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            if len(parts) < 4:
                sys.stderr.write(f"Warning: {args.tbl_path}:{line_num}: invalid line format: {line}\n")
                continue
            try:
                nr = int(parts[0])
            except ValueError:
                sys.stderr.write(f"Error: {args.tbl_path}:{line_num}: invalid syscall number '{parts[0]}'\n")
                sys.exit(1)
            abi = parts[1]
            name = parts[2]
            entry_point = parts[3]

            if nr >= TABLE_SIZE:
                sys.stderr.write(f"Error: syscall {nr} ({name}) exceeds TABLE_SIZE {TABLE_SIZE}\n")
                sys.exit(1)

            if nr in seen_nrs:
                sys.stderr.write(f"Error: duplicate syscall number {nr} on line {line_num} (previous was {seen_nrs[nr]})\n")
                sys.exit(1)

            seen_nrs[nr] = name
            entries.append((nr, abi, name, entry_point))

    entries.sort(key=lambda x: x[0])

    # Distinct function names for forward declarations
    unique_fns = sorted(list({e[3] for e in entries}))

    lines = [
        "/* SPDX-License-Identifier: GPL-2.0-only WITH Linux-syscall-note */",
        "/* ============================================================================",
        " * AzamiOS — Generated System Call Table Header",
        f" * Auto-generated by scripts/gensyscalltbl.py from {args.tbl_path}",
        " * DO NOT EDIT DIRECTLY.",
        " * ============================================================================ */",
        "#pragma once",
        "",
        '#include "../../include/azami/types.h"',
        '#include "../../arch/x86_64/cpu/idt.h" /* pt_regs_t */',
        "",
        f"#define SYSCALL_TABLE_SIZE {TABLE_SIZE}",
        f"#define SYSCALL_COUNT      {len(entries)}",
        "",
        "typedef s64 (*syscall_fn_t)(pt_regs_t *r);",
        "",
        "/* ── Forward Declarations for Syscall Handlers ────────────────────────── */"
    ]

    for fn in unique_fns:
        lines.append(f"s64 {fn}(pt_regs_t *r);")

    lines.append("")
    lines.append("/* ── Static Dispatch Table Initializer ────────────────────────────────── */")
    lines.append("#define __SYSCALL_TABLE_INITIALIZER { \\")
    for nr, abi, name, fn in entries:
        lines.append(f"    [{nr:<3}] = {fn}, /* {name} ({abi}) */ \\")
    lines.append("}")
    lines.append("")

    content = "\n".join(lines) + "\n"

    # Only write if modified to avoid touching timestamps needlessly
    if os.path.exists(args.out_path):
        with open(args.out_path, "r") as f:
            existing = f.read()
        if existing == content:
            return

    with open(args.out_path, "w") as f:
        f.write(content)

    print(f"Generated {args.out_path} ({len(entries)} syscalls, max nr {entries[-1][0]})")

if __name__ == "__main__":
    main()

