/* ============================================================================
 * AzamiOS Userspace — Auto-Accept & Unattended Policy Controller (autoaccept.elf)
 * File: userland/apps/autoaccept/main.c
 *
 * Provides a dedicated CLI tool to query, toggle, script, and manage the
 * AzamiOS Auto-Accept and Unattended Execution security policies.
 * ============================================================================ */

#include "../../libc/include/stdio.h"
#include "../../libc/include/stdlib.h"
#include "../../libc/include/string.h"
#include "../../libc/include/stdbool.h"
#include "../../libc/include/unistd.h"
#include "../../libc/include/fcntl.h"
#include "../../libc/include/sys/stat.h"
#include "../../libc/include/sys/wait.h"

#define SECURITY_CONF_PATH "/etc/security.conf"
#define MAX_CONF_SIZE 4096

typedef struct {
    const char *key;
    const char *label;
    const char *desc;
    bool active;
} policy_entry_t;

static policy_entry_t s_policies[] = {
    { "ipc_autoaccept",   "IPC Capability Transfers", "SCM_RIGHTS file descriptor & IPC capability passing", false },
    { "admin_autoaccept", "Desktop Administrative",  "Unattended desktop admin & elevation prompts",       false },
    { "dhcp_autoaccept",  "Network DHCP Transitions", "Seamless network interface lease transitions",        false },
    { "trace_autoaccept", "System Tracing & Hooks",   "Kernel function tracing & telemetry probes",          false }
};
#define NUM_POLICIES (sizeof(s_policies) / sizeof(s_policies[0]))

static void load_policies(void)
{
    int fd = open(SECURITY_CONF_PATH, O_RDONLY, 0);
    if (fd < 0) {
        /* Default to active if config doesn't exist yet */
        for (size_t i = 0; i < NUM_POLICIES; i++) {
            s_policies[i].active = true;
        }
        return;
    }

    char buf[MAX_CONF_SIZE];
    ssize_t n = read(fd, buf, sizeof(buf) - 1);
    close(fd);
    if (n < 0) n = 0;
    buf[n] = '\0';

    char *line = buf;
    while (*line) {
        char *end = strchr(line, '\n');
        if (end) *end = '\0';

        while (*line == ' ' || *line == '\t') line++;
        if (*line != '#' && *line != '\0') {
            char *eq = strchr(line, '=');
            if (eq) {
                *eq = '\0';
                char *val = eq + 1;
                while (*val == ' ' || *val == '\t') val++;
                for (size_t i = 0; i < NUM_POLICIES; i++) {
                    if (strcmp(line, s_policies[i].key) == 0) {
                        s_policies[i].active = (atoi(val) == 1 || strcmp(val, "true") == 0);
                        break;
                    }
                }
            }
        }

        if (!end) break;
        line = end + 1;
    }
}

static int save_policies(void)
{
    char buf[MAX_CONF_SIZE];
    size_t pos = 0;

    pos += snprintf(buf + pos, sizeof(buf) - pos,
                    "# AzamiOS Auto-Accept & Security Policies\n"
                    "# Generated by autoaccept CLI / Settings Control Panel\n\n");

    for (size_t i = 0; i < NUM_POLICIES; i++) {
        pos += snprintf(buf + pos, sizeof(buf) - pos, "%s=%d\n",
                        s_policies[i].key, s_policies[i].active ? 1 : 0);
    }

    int fd = open(SECURITY_CONF_PATH, O_WRONLY | O_CREAT | O_TRUNC, 0644);
    if (fd < 0) {
        perror("autoaccept: failed to open " SECURITY_CONF_PATH);
        return -1;
    }

    ssize_t written = write(fd, buf, pos);
    close(fd);
    return (written == (ssize_t)pos) ? 0 : -1;
}

static void print_usage(const char *prog)
{
    printf("\033[1;35mAzamiOS Auto-Accept & Unattended Execution CLI\033[0m\n\n");
    printf("Usage: %s <command> [arguments]\n\n", prog);
    printf("Commands:\n");
    printf("  \033[1;36mstatus\033[0m                      Display all auto-accept policy states\n");
    printf("  \033[1;36menable\033[0m  <policy|all>        Enable specified auto-accept policy or all\n");
    printf("  \033[1;36mdisable\033[0m <policy|all>        Disable specified auto-accept policy or all\n");
    printf("  \033[1;36mon\033[0m     <policy|all>        Alias for enable\n");
    printf("  \033[1;36moff\033[0m    <policy|all>        Alias for disable\n");
    printf("  \033[1;36mcheck\033[0m  <policy>            Exit 0 if policy is active, 1 otherwise\n");
    printf("  \033[1;36mrun\033[0m    <command...>        Execute command with full auto-accept privileges\n");
    printf("  \033[1;36m-h, --help\033[0m                 Display this help message and exit\n");
    printf("  \033[1;36m-V, --version\033[0m              Display version information and exit\n\n");
    printf("Policies: ipc, admin, dhcp, trace, all\n");
}

static void do_status(void)
{
    load_policies();

    printf("\033[1;37mAzamiOS Auto-Accept & Unattended Policy Matrix\033[0m\n");
    printf("Config File: %s\n", SECURITY_CONF_PATH);
    printf("----------------------------------------------------------------------\n");
    printf("%-18s %-26s %-10s %s\n", "KEY", "SUBSYSTEM", "STATE", "DESCRIPTION");
    printf("----------------------------------------------------------------------\n");

    bool all_active = true;
    for (size_t i = 0; i < NUM_POLICIES; i++) {
        if (!s_policies[i].active) all_active = false;
        printf("\033[1;36m%-18s\033[0m %-26s %s%-10s\033[0m %s\n",
               s_policies[i].key,
               s_policies[i].label,
               s_policies[i].active ? "\033[1;32m" : "\033[1;31m",
               s_policies[i].active ? "ENABLED" : "DISABLED",
               s_policies[i].desc);
    }
    printf("----------------------------------------------------------------------\n");

    if (all_active) {
        printf("\033[1;32m[+] Auto-Accept Global State: FULLY ACTIVE (Zero-prompt unattended mode)\033[0m\n");
    } else {
        printf("\033[1;33m[!] Auto-Accept Global State: PARTIAL (Some operations require interactive prompts)\033[0m\n");
    }
}

static int do_set(const char *target, bool enable)
{
    load_policies();
    bool found = false;

    if (strcmp(target, "all") == 0) {
        for (size_t i = 0; i < NUM_POLICIES; i++) {
            s_policies[i].active = enable;
        }
        found = true;
    } else {
        for (size_t i = 0; i < NUM_POLICIES; i++) {
            if (strcmp(target, s_policies[i].key) == 0 ||
                strstr(s_policies[i].key, target) != NULL) {
                s_policies[i].active = enable;
                found = true;
                break;
            }
        }
    }

    if (!found) {
        fprintf(stderr, "autoaccept: unknown policy '%s'. Valid options: ipc, admin, dhcp, trace, all\n", target);
        return 1;
    }

    if (save_policies() != 0) {
        return 1;
    }

    printf("\033[1;32m[✓]\033[0m Policy '%s' successfully set to \033[1m%s\033[0m.\n",
           target, enable ? "ENABLED" : "DISABLED");
    return 0;
}

static int do_check(const char *target)
{
    load_policies();
    for (size_t i = 0; i < NUM_POLICIES; i++) {
        if (strcmp(target, s_policies[i].key) == 0 ||
            strstr(s_policies[i].key, target) != NULL) {
            return s_policies[i].active ? 0 : 1;
        }
    }
    return 1;
}

static int do_run(int argc, char **argv)
{
    if (argc < 2) {
        fprintf(stderr, "autoaccept run: missing command to execute\n");
        return 1;
    }

    /* Set environment variable indicating auto-accept unattended mode */
    setenv("AZ_AUTOACCEPT", "1", 1);
    setenv("DEBIAN_FRONTEND", "noninteractive", 1);

    pid_t pid = fork();
    if (pid == 0) {
        execvp(argv[1], &argv[1]);
        perror("autoaccept run execvp");
        _exit(127);
    } else if (pid > 0) {
        int status = 0;
        waitpid(pid, &status, 0);
        if (WIFEXITED(status)) {
            return WEXITSTATUS(status);
        }
        return 1;
    } else {
        perror("autoaccept fork");
        return 1;
    }
}

int main(int argc, char **argv)
{
    if (argc < 2) {
        do_status();
        return 0;
    }

    if (strcmp(argv[1], "--help") == 0 || strcmp(argv[1], "-h") == 0) {
        print_usage(argv[0]);
        return 0;
    }

    if (strcmp(argv[1], "--version") == 0 || strcmp(argv[1], "-V") == 0) {
        printf("autoaccept (AzamiOS Policy Engine) 7.0.0\n");
        return 0;
    }

    if (strcmp(argv[1], "status") == 0) {
        do_status();
        return 0;
    }

    if (strcmp(argv[1], "enable") == 0 || strcmp(argv[1], "on") == 0) {
        const char *target = (argc >= 3) ? argv[2] : "all";
        return do_set(target, true);
    }

    if (strcmp(argv[1], "disable") == 0 || strcmp(argv[1], "off") == 0) {
        const char *target = (argc >= 3) ? argv[2] : "all";
        return do_set(target, false);
    }

    if (strcmp(argv[1], "check") == 0) {
        if (argc < 3) {
            fprintf(stderr, "autoaccept check: missing policy operand\n");
            return 1;
        }
        return do_check(argv[2]);
    }

    if (strcmp(argv[1], "run") == 0) {
        return do_run(argc - 1, &argv[1]);
    }

    fprintf(stderr, "autoaccept: unrecognized command '%s'\nTry 'autoaccept --help' for more information.\n", argv[1]);
    return 1;
}
