/* SPDX-License-Identifier: GPL-2.0-only WITH Linux-syscall-note */
/* ============================================================================
 * AzamiOS — Generated System Call Table Header
 * Auto-generated by scripts/gensyscalltbl.py from kernel/syscall/syscalls.tbl
 * DO NOT EDIT DIRECTLY.
 * ============================================================================ */
#pragma once

#include "../../include/azami/types.h"
#include "../../arch/x86_64/cpu/idt.h" /* pt_regs_t */

#define SYSCALL_TABLE_SIZE 560
#define SYSCALL_COUNT      385

typedef s64 (*syscall_fn_t)(pt_regs_t *r);

/* ── Forward Declarations for Syscall Handlers ────────────────────────── */
s64 sys_accept4_impl(pt_regs_t *r);
s64 sys_accept_impl(pt_regs_t *r);
s64 sys_access_impl(pt_regs_t *r);
s64 sys_acct_impl(pt_regs_t *r);
s64 sys_add_key_impl(pt_regs_t *r);
s64 sys_adjtimex_impl(pt_regs_t *r);
s64 sys_alarm_impl(pt_regs_t *r);
s64 sys_arch_prctl_impl(pt_regs_t *r);
s64 sys_az_channel_create(pt_regs_t *r);
s64 sys_az_channel_destroy(pt_regs_t *r);
s64 sys_az_channel_recv(pt_regs_t *r);
s64 sys_az_channel_send(pt_regs_t *r);
s64 sys_az_fb_flip(pt_regs_t *r);
s64 sys_az_fb_info(pt_regs_t *r);
s64 sys_az_fb_map(pt_regs_t *r);
s64 sys_az_ktrace_clear_impl(pt_regs_t *r);
s64 sys_az_ktrace_enable_impl(pt_regs_t *r);
s64 sys_az_ktrace_read_impl(pt_regs_t *r);
s64 sys_az_object_close(pt_regs_t *r);
s64 sys_az_object_create(pt_regs_t *r);
s64 sys_az_object_open(pt_regs_t *r);
s64 sys_az_sem_close_impl(pt_regs_t *r);
s64 sys_az_sem_getvalue_impl(pt_regs_t *r);
s64 sys_az_sem_open_impl(pt_regs_t *r);
s64 sys_az_sem_post_impl(pt_regs_t *r);
s64 sys_az_sem_timedwait_impl(pt_regs_t *r);
s64 sys_az_sem_trywait_impl(pt_regs_t *r);
s64 sys_az_sem_unlink_impl(pt_regs_t *r);
s64 sys_az_sem_wait_impl(pt_regs_t *r);
s64 sys_az_set_timer_impl(pt_regs_t *r);
s64 sys_az_shmem_create(pt_regs_t *r);
s64 sys_az_shmem_destroy(pt_regs_t *r);
s64 sys_az_shmem_map(pt_regs_t *r);
s64 sys_az_shmem_unmap(pt_regs_t *r);
s64 sys_az_spawn(pt_regs_t *r);
s64 sys_az_spawn_arg(pt_regs_t *r);
s64 sys_az_sysstat_impl(pt_regs_t *r);
s64 sys_az_thread_create_impl(pt_regs_t *r);
s64 sys_az_thread_exit_impl(pt_regs_t *r);
s64 sys_az_yield(pt_regs_t *r);
s64 sys_bind_impl(pt_regs_t *r);
s64 sys_bpf_impl(pt_regs_t *r);
s64 sys_brk_impl(pt_regs_t *r);
s64 sys_cachestat_impl(pt_regs_t *r);
s64 sys_capget_impl(pt_regs_t *r);
s64 sys_capset_impl(pt_regs_t *r);
s64 sys_chdir_impl(pt_regs_t *r);
s64 sys_chmod_impl(pt_regs_t *r);
s64 sys_chown_impl(pt_regs_t *r);
s64 sys_chroot_impl(pt_regs_t *r);
s64 sys_clock_adjtime_impl(pt_regs_t *r);
s64 sys_clock_getres_impl(pt_regs_t *r);
s64 sys_clock_gettime_impl(pt_regs_t *r);
s64 sys_clock_nanosleep_impl(pt_regs_t *r);
s64 sys_clock_settime_impl(pt_regs_t *r);
s64 sys_clone3_impl(pt_regs_t *r);
s64 sys_clone_impl(pt_regs_t *r);
s64 sys_close_impl(pt_regs_t *r);
s64 sys_close_range_impl(pt_regs_t *r);
s64 sys_connect_impl(pt_regs_t *r);
s64 sys_copy_file_range_impl(pt_regs_t *r);
s64 sys_creat_impl(pt_regs_t *r);
s64 sys_dup2_impl(pt_regs_t *r);
s64 sys_dup3_impl(pt_regs_t *r);
s64 sys_dup_impl(pt_regs_t *r);
s64 sys_epoll_create1_impl(pt_regs_t *r);
s64 sys_epoll_create_impl(pt_regs_t *r);
s64 sys_epoll_ctl_impl(pt_regs_t *r);
s64 sys_epoll_pwait2_impl(pt_regs_t *r);
s64 sys_epoll_pwait_impl(pt_regs_t *r);
s64 sys_epoll_wait_impl(pt_regs_t *r);
s64 sys_eventfd2_impl(pt_regs_t *r);
s64 sys_eventfd_impl(pt_regs_t *r);
s64 sys_execve_impl(pt_regs_t *r);
s64 sys_execveat_impl(pt_regs_t *r);
s64 sys_exit_group_impl(pt_regs_t *r);
s64 sys_exit_impl(pt_regs_t *r);
s64 sys_faccessat2_impl(pt_regs_t *r);
s64 sys_faccessat_impl(pt_regs_t *r);
s64 sys_fadvise64_impl(pt_regs_t *r);
s64 sys_fallocate_impl(pt_regs_t *r);
s64 sys_fanotify_init_impl(pt_regs_t *r);
s64 sys_fanotify_mark_impl(pt_regs_t *r);
s64 sys_fchdir_impl(pt_regs_t *r);
s64 sys_fchmod_impl(pt_regs_t *r);
s64 sys_fchmodat2_impl(pt_regs_t *r);
s64 sys_fchmodat_impl(pt_regs_t *r);
s64 sys_fchown_impl(pt_regs_t *r);
s64 sys_fchownat_impl(pt_regs_t *r);
s64 sys_fcntl_impl(pt_regs_t *r);
s64 sys_fdatasync_impl(pt_regs_t *r);
s64 sys_fgetxattr_impl(pt_regs_t *r);
s64 sys_finit_module_impl(pt_regs_t *r);
s64 sys_flistxattr_impl(pt_regs_t *r);
s64 sys_flock_impl(pt_regs_t *r);
s64 sys_fork_impl(pt_regs_t *r);
s64 sys_fremovexattr_impl(pt_regs_t *r);
s64 sys_fsconfig_impl(pt_regs_t *r);
s64 sys_fsetxattr_impl(pt_regs_t *r);
s64 sys_fsmount_impl(pt_regs_t *r);
s64 sys_fsopen_impl(pt_regs_t *r);
s64 sys_fspick_impl(pt_regs_t *r);
s64 sys_fstat_impl(pt_regs_t *r);
s64 sys_fstatat_impl(pt_regs_t *r);
s64 sys_fstatfs_impl(pt_regs_t *r);
s64 sys_fsync_impl(pt_regs_t *r);
s64 sys_ftruncate_impl(pt_regs_t *r);
s64 sys_futex_impl(pt_regs_t *r);
s64 sys_futex_requeue_impl(pt_regs_t *r);
s64 sys_futex_wait_impl(pt_regs_t *r);
s64 sys_futex_waitv_impl(pt_regs_t *r);
s64 sys_futex_wake_impl(pt_regs_t *r);
s64 sys_futimesat_impl(pt_regs_t *r);
s64 sys_get_mempolicy_impl(pt_regs_t *r);
s64 sys_get_robust_list_impl(pt_regs_t *r);
s64 sys_getcpu_impl(pt_regs_t *r);
s64 sys_getcwd_impl(pt_regs_t *r);
s64 sys_getdents64_impl(pt_regs_t *r);
s64 sys_getdents_impl(pt_regs_t *r);
s64 sys_getegid_impl(pt_regs_t *r);
s64 sys_geteuid_impl(pt_regs_t *r);
s64 sys_getfacl_impl(pt_regs_t *r);
s64 sys_getgid_impl(pt_regs_t *r);
s64 sys_getgroups_impl(pt_regs_t *r);
s64 sys_getitimer_impl(pt_regs_t *r);
s64 sys_getpeername_impl(pt_regs_t *r);
s64 sys_getpgid_impl(pt_regs_t *r);
s64 sys_getpgrp_impl(pt_regs_t *r);
s64 sys_getpid_impl(pt_regs_t *r);
s64 sys_getppid_impl(pt_regs_t *r);
s64 sys_getpriority_impl(pt_regs_t *r);
s64 sys_getrandom_impl(pt_regs_t *r);
s64 sys_getresgid_impl(pt_regs_t *r);
s64 sys_getresuid_impl(pt_regs_t *r);
s64 sys_getrlimit_impl(pt_regs_t *r);
s64 sys_getrusage_impl(pt_regs_t *r);
s64 sys_getsid_impl(pt_regs_t *r);
s64 sys_getsockname_impl(pt_regs_t *r);
s64 sys_getsockopt_impl(pt_regs_t *r);
s64 sys_gettid_impl(pt_regs_t *r);
s64 sys_gettimeofday_impl(pt_regs_t *r);
s64 sys_getuid_impl(pt_regs_t *r);
s64 sys_getxattr_impl(pt_regs_t *r);
s64 sys_inotify_add_watch_impl(pt_regs_t *r);
s64 sys_inotify_init1_impl(pt_regs_t *r);
s64 sys_inotify_init_impl(pt_regs_t *r);
s64 sys_inotify_rm_watch_impl(pt_regs_t *r);
s64 sys_io_cancel_impl(pt_regs_t *r);
s64 sys_io_destroy_impl(pt_regs_t *r);
s64 sys_io_getevents_impl(pt_regs_t *r);
s64 sys_io_pgetevents_impl(pt_regs_t *r);
s64 sys_io_setup_impl(pt_regs_t *r);
s64 sys_io_submit_impl(pt_regs_t *r);
s64 sys_io_uring_enter_impl(pt_regs_t *r);
s64 sys_io_uring_register_impl(pt_regs_t *r);
s64 sys_io_uring_setup_impl(pt_regs_t *r);
s64 sys_ioctl_impl(pt_regs_t *r);
s64 sys_ioperm_impl(pt_regs_t *r);
s64 sys_iopl_impl(pt_regs_t *r);
s64 sys_ioprio_get_impl(pt_regs_t *r);
s64 sys_ioprio_set_impl(pt_regs_t *r);
s64 sys_kcmp_impl(pt_regs_t *r);
s64 sys_kexec_file_load_impl(pt_regs_t *r);
s64 sys_keyctl_impl(pt_regs_t *r);
s64 sys_kill_impl(pt_regs_t *r);
s64 sys_landlock_add_rule_impl(pt_regs_t *r);
s64 sys_landlock_create_ruleset_impl(pt_regs_t *r);
s64 sys_landlock_restrict_self_impl(pt_regs_t *r);
s64 sys_lchown_impl(pt_regs_t *r);
s64 sys_lgetxattr_impl(pt_regs_t *r);
s64 sys_link_impl(pt_regs_t *r);
s64 sys_linkat_impl(pt_regs_t *r);
s64 sys_listen_impl(pt_regs_t *r);
s64 sys_listmount_impl(pt_regs_t *r);
s64 sys_listxattr_impl(pt_regs_t *r);
s64 sys_llistxattr_impl(pt_regs_t *r);
s64 sys_lremovexattr_impl(pt_regs_t *r);
s64 sys_lseek_impl(pt_regs_t *r);
s64 sys_lsetxattr_impl(pt_regs_t *r);
s64 sys_lsm_get_self_attr_impl(pt_regs_t *r);
s64 sys_lsm_list_modules_impl(pt_regs_t *r);
s64 sys_lsm_set_self_attr_impl(pt_regs_t *r);
s64 sys_lstat_impl(pt_regs_t *r);
s64 sys_madvise_impl(pt_regs_t *r);
s64 sys_map_shadow_stack_impl(pt_regs_t *r);
s64 sys_mbind_impl(pt_regs_t *r);
s64 sys_membarrier_impl(pt_regs_t *r);
s64 sys_memfd_create_impl(pt_regs_t *r);
s64 sys_memfd_secret_impl(pt_regs_t *r);
s64 sys_migrate_pages_impl(pt_regs_t *r);
s64 sys_mincore_impl(pt_regs_t *r);
s64 sys_mkdir_impl(pt_regs_t *r);
s64 sys_mkdirat_impl(pt_regs_t *r);
s64 sys_mknod_impl(pt_regs_t *r);
s64 sys_mknodat_impl(pt_regs_t *r);
s64 sys_mlock2_impl(pt_regs_t *r);
s64 sys_mlock_impl(pt_regs_t *r);
s64 sys_mlockall_impl(pt_regs_t *r);
s64 sys_mmap_impl(pt_regs_t *r);
s64 sys_mount_impl(pt_regs_t *r);
s64 sys_mount_setattr_impl(pt_regs_t *r);
s64 sys_move_mount_impl(pt_regs_t *r);
s64 sys_move_pages_impl(pt_regs_t *r);
s64 sys_mprotect_impl(pt_regs_t *r);
s64 sys_mq_getsetattr_impl(pt_regs_t *r);
s64 sys_mq_notify_impl(pt_regs_t *r);
s64 sys_mq_open_impl(pt_regs_t *r);
s64 sys_mq_timedreceive_impl(pt_regs_t *r);
s64 sys_mq_timedsend_impl(pt_regs_t *r);
s64 sys_mq_unlink_impl(pt_regs_t *r);
s64 sys_mremap_impl(pt_regs_t *r);
s64 sys_mseal_impl(pt_regs_t *r);
s64 sys_msgctl_impl(pt_regs_t *r);
s64 sys_msgget_impl(pt_regs_t *r);
s64 sys_msgrcv_impl(pt_regs_t *r);
s64 sys_msgsnd_impl(pt_regs_t *r);
s64 sys_msync_impl(pt_regs_t *r);
s64 sys_munlock_impl(pt_regs_t *r);
s64 sys_munlockall_impl(pt_regs_t *r);
s64 sys_munmap_impl(pt_regs_t *r);
s64 sys_name_to_handle_at_impl(pt_regs_t *r);
s64 sys_nanosleep_impl(pt_regs_t *r);
s64 sys_open_by_handle_at_impl(pt_regs_t *r);
s64 sys_open_impl(pt_regs_t *r);
s64 sys_open_tree_impl(pt_regs_t *r);
s64 sys_openat2_impl(pt_regs_t *r);
s64 sys_openat_impl(pt_regs_t *r);
s64 sys_pause_impl(pt_regs_t *r);
s64 sys_perf_event_open_impl(pt_regs_t *r);
s64 sys_personality_impl(pt_regs_t *r);
s64 sys_pidfd_getfd_impl(pt_regs_t *r);
s64 sys_pidfd_open_impl(pt_regs_t *r);
s64 sys_pidfd_send_signal_impl(pt_regs_t *r);
s64 sys_pipe2_impl(pt_regs_t *r);
s64 sys_pipe_impl(pt_regs_t *r);
s64 sys_pivot_root_impl(pt_regs_t *r);
s64 sys_pkey_alloc_impl(pt_regs_t *r);
s64 sys_pkey_free_impl(pt_regs_t *r);
s64 sys_pkey_mprotect_impl(pt_regs_t *r);
s64 sys_poll_impl(pt_regs_t *r);
s64 sys_ppoll_impl(pt_regs_t *r);
s64 sys_prctl_impl(pt_regs_t *r);
s64 sys_pread64_impl(pt_regs_t *r);
s64 sys_preadv_impl(pt_regs_t *r);
s64 sys_prlimit64_impl(pt_regs_t *r);
s64 sys_process_madvise_impl(pt_regs_t *r);
s64 sys_process_mrelease_impl(pt_regs_t *r);
s64 sys_process_vm_readv_impl(pt_regs_t *r);
s64 sys_process_vm_writev_impl(pt_regs_t *r);
s64 sys_pselect6_impl(pt_regs_t *r);
s64 sys_ptrace_impl(pt_regs_t *r);
s64 sys_pwrite64_impl(pt_regs_t *r);
s64 sys_pwritev_impl(pt_regs_t *r);
s64 sys_quotactl_fd_impl(pt_regs_t *r);
s64 sys_read_impl(pt_regs_t *r);
s64 sys_readahead_impl(pt_regs_t *r);
s64 sys_readlink_impl(pt_regs_t *r);
s64 sys_readlinkat_impl(pt_regs_t *r);
s64 sys_readv_impl(pt_regs_t *r);
s64 sys_reboot_impl(pt_regs_t *r);
s64 sys_recvfrom_impl(pt_regs_t *r);
s64 sys_recvmmsg_impl(pt_regs_t *r);
s64 sys_recvmsg_impl(pt_regs_t *r);
s64 sys_removexattr_impl(pt_regs_t *r);
s64 sys_rename_impl(pt_regs_t *r);
s64 sys_renameat2_impl(pt_regs_t *r);
s64 sys_renameat_impl(pt_regs_t *r);
s64 sys_request_key_impl(pt_regs_t *r);
s64 sys_restart_syscall_impl(pt_regs_t *r);
s64 sys_rmdir_impl(pt_regs_t *r);
s64 sys_rseq_impl(pt_regs_t *r);
s64 sys_rt_sigaction_impl(pt_regs_t *r);
s64 sys_rt_sigpending_impl(pt_regs_t *r);
s64 sys_rt_sigprocmask_impl(pt_regs_t *r);
s64 sys_rt_sigqueueinfo_impl(pt_regs_t *r);
s64 sys_rt_sigreturn_impl(pt_regs_t *r);
s64 sys_rt_sigsuspend_impl(pt_regs_t *r);
s64 sys_rt_sigtimedwait_impl(pt_regs_t *r);
s64 sys_rt_tgsigqueueinfo_impl(pt_regs_t *r);
s64 sys_sched_get_priority_max_impl(pt_regs_t *r);
s64 sys_sched_get_priority_min_impl(pt_regs_t *r);
s64 sys_sched_getaffinity_impl(pt_regs_t *r);
s64 sys_sched_getattr_impl(pt_regs_t *r);
s64 sys_sched_getparam_impl(pt_regs_t *r);
s64 sys_sched_getscheduler_impl(pt_regs_t *r);
s64 sys_sched_rr_get_interval_impl(pt_regs_t *r);
s64 sys_sched_setaffinity_impl(pt_regs_t *r);
s64 sys_sched_setattr_impl(pt_regs_t *r);
s64 sys_sched_setparam_impl(pt_regs_t *r);
s64 sys_sched_setscheduler_impl(pt_regs_t *r);
s64 sys_sched_yield_impl(pt_regs_t *r);
s64 sys_seccomp_impl(pt_regs_t *r);
s64 sys_select_impl(pt_regs_t *r);
s64 sys_semctl_impl(pt_regs_t *r);
s64 sys_semget_impl(pt_regs_t *r);
s64 sys_semop_impl(pt_regs_t *r);
s64 sys_semtimedop_impl(pt_regs_t *r);
s64 sys_sendfile_impl(pt_regs_t *r);
s64 sys_sendmmsg_impl(pt_regs_t *r);
s64 sys_sendmsg_impl(pt_regs_t *r);
s64 sys_sendto_impl(pt_regs_t *r);
s64 sys_set_mempolicy_home_node_impl(pt_regs_t *r);
s64 sys_set_mempolicy_impl(pt_regs_t *r);
s64 sys_set_robust_list_impl(pt_regs_t *r);
s64 sys_set_tid_address_impl(pt_regs_t *r);
s64 sys_setdomainname_impl(pt_regs_t *r);
s64 sys_setfacl_impl(pt_regs_t *r);
s64 sys_setfsgid_impl(pt_regs_t *r);
s64 sys_setfsuid_impl(pt_regs_t *r);
s64 sys_setgid_impl(pt_regs_t *r);
s64 sys_setgroups_impl(pt_regs_t *r);
s64 sys_sethostname_impl(pt_regs_t *r);
s64 sys_setitimer_impl(pt_regs_t *r);
s64 sys_setns_impl(pt_regs_t *r);
s64 sys_setpgid_impl(pt_regs_t *r);
s64 sys_setpriority_impl(pt_regs_t *r);
s64 sys_setregid_impl(pt_regs_t *r);
s64 sys_setresgid_impl(pt_regs_t *r);
s64 sys_setresuid_impl(pt_regs_t *r);
s64 sys_setreuid_impl(pt_regs_t *r);
s64 sys_setrlimit_impl(pt_regs_t *r);
s64 sys_setsid_impl(pt_regs_t *r);
s64 sys_setsockopt_impl(pt_regs_t *r);
s64 sys_settimeofday_impl(pt_regs_t *r);
s64 sys_setuid_impl(pt_regs_t *r);
s64 sys_setxattr_impl(pt_regs_t *r);
s64 sys_shmat_impl(pt_regs_t *r);
s64 sys_shmctl_impl(pt_regs_t *r);
s64 sys_shmdt_impl(pt_regs_t *r);
s64 sys_shmget_impl(pt_regs_t *r);
s64 sys_shutdown_impl(pt_regs_t *r);
s64 sys_sigaltstack_impl(pt_regs_t *r);
s64 sys_signalfd4_impl(pt_regs_t *r);
s64 sys_signalfd_impl(pt_regs_t *r);
s64 sys_socket_impl(pt_regs_t *r);
s64 sys_socketpair_impl(pt_regs_t *r);
s64 sys_splice_impl(pt_regs_t *r);
s64 sys_stat_impl(pt_regs_t *r);
s64 sys_statfs_impl(pt_regs_t *r);
s64 sys_statmount_impl(pt_regs_t *r);
s64 sys_statx_impl(pt_regs_t *r);
s64 sys_swapoff_impl(pt_regs_t *r);
s64 sys_swapon_impl(pt_regs_t *r);
s64 sys_symlink_impl(pt_regs_t *r);
s64 sys_symlinkat_impl(pt_regs_t *r);
s64 sys_sync_file_range_impl(pt_regs_t *r);
s64 sys_sync_impl(pt_regs_t *r);
s64 sys_syncfs_impl(pt_regs_t *r);
s64 sys_sysinfo_impl(pt_regs_t *r);
s64 sys_syslog_impl(pt_regs_t *r);
s64 sys_tee_impl(pt_regs_t *r);
s64 sys_tgkill_impl(pt_regs_t *r);
s64 sys_time_impl(pt_regs_t *r);
s64 sys_timer_create_impl(pt_regs_t *r);
s64 sys_timer_delete_impl(pt_regs_t *r);
s64 sys_timer_getoverrun_impl(pt_regs_t *r);
s64 sys_timer_gettime_impl(pt_regs_t *r);
s64 sys_timer_settime_impl(pt_regs_t *r);
s64 sys_timerfd_create_impl(pt_regs_t *r);
s64 sys_timerfd_gettime_impl(pt_regs_t *r);
s64 sys_timerfd_settime_impl(pt_regs_t *r);
s64 sys_times_impl(pt_regs_t *r);
s64 sys_tkill_impl(pt_regs_t *r);
s64 sys_truncate_impl(pt_regs_t *r);
s64 sys_umask_impl(pt_regs_t *r);
s64 sys_umount2_impl(pt_regs_t *r);
s64 sys_uname_impl(pt_regs_t *r);
s64 sys_unlink_impl(pt_regs_t *r);
s64 sys_unlinkat_impl(pt_regs_t *r);
s64 sys_unshare_impl(pt_regs_t *r);
s64 sys_userfaultfd_impl(pt_regs_t *r);
s64 sys_utime_impl(pt_regs_t *r);
s64 sys_utimensat_impl(pt_regs_t *r);
s64 sys_utimes_impl(pt_regs_t *r);
s64 sys_vfork_impl(pt_regs_t *r);
s64 sys_vhangup_impl(pt_regs_t *r);
s64 sys_vmsplice_impl(pt_regs_t *r);
s64 sys_wait4_impl(pt_regs_t *r);
s64 sys_waitid_impl(pt_regs_t *r);
s64 sys_write_impl(pt_regs_t *r);
s64 sys_writev_impl(pt_regs_t *r);

/* ── Static Dispatch Table Initializer ────────────────────────────────── */
#define __SYSCALL_TABLE_INITIALIZER { \
    [0  ] = sys_read_impl, /* read (common) */ \
    [1  ] = sys_write_impl, /* write (common) */ \
    [2  ] = sys_open_impl, /* open (common) */ \
    [3  ] = sys_close_impl, /* close (common) */ \
    [4  ] = sys_stat_impl, /* stat (common) */ \
    [5  ] = sys_fstat_impl, /* fstat (common) */ \
    [6  ] = sys_lstat_impl, /* lstat (common) */ \
    [7  ] = sys_poll_impl, /* poll (common) */ \
    [8  ] = sys_lseek_impl, /* lseek (common) */ \
    [9  ] = sys_mmap_impl, /* mmap (common) */ \
    [10 ] = sys_mprotect_impl, /* mprotect (common) */ \
    [11 ] = sys_munmap_impl, /* munmap (common) */ \
    [12 ] = sys_brk_impl, /* brk (common) */ \
    [13 ] = sys_rt_sigaction_impl, /* rt_sigaction (common) */ \
    [14 ] = sys_rt_sigprocmask_impl, /* rt_sigprocmask (common) */ \
    [15 ] = sys_rt_sigreturn_impl, /* rt_sigreturn (common) */ \
    [16 ] = sys_ioctl_impl, /* ioctl (common) */ \
    [17 ] = sys_pread64_impl, /* pread64 (common) */ \
    [18 ] = sys_pwrite64_impl, /* pwrite64 (common) */ \
    [19 ] = sys_readv_impl, /* readv (common) */ \
    [20 ] = sys_writev_impl, /* writev (common) */ \
    [21 ] = sys_access_impl, /* access (common) */ \
    [22 ] = sys_pipe_impl, /* pipe (common) */ \
    [23 ] = sys_select_impl, /* select (common) */ \
    [24 ] = sys_sched_yield_impl, /* sched_yield (common) */ \
    [25 ] = sys_mremap_impl, /* mremap (common) */ \
    [26 ] = sys_msync_impl, /* msync (common) */ \
    [27 ] = sys_mincore_impl, /* mincore (common) */ \
    [28 ] = sys_madvise_impl, /* madvise (common) */ \
    [29 ] = sys_shmget_impl, /* shmget (common) */ \
    [30 ] = sys_shmat_impl, /* shmat (common) */ \
    [31 ] = sys_shmctl_impl, /* shmctl (common) */ \
    [32 ] = sys_dup_impl, /* dup (common) */ \
    [33 ] = sys_dup2_impl, /* dup2 (common) */ \
    [34 ] = sys_pause_impl, /* pause (common) */ \
    [35 ] = sys_nanosleep_impl, /* nanosleep (common) */ \
    [36 ] = sys_getitimer_impl, /* getitimer (common) */ \
    [37 ] = sys_alarm_impl, /* alarm (common) */ \
    [38 ] = sys_setitimer_impl, /* setitimer (common) */ \
    [39 ] = sys_getpid_impl, /* getpid (common) */ \
    [40 ] = sys_sendfile_impl, /* sendfile (common) */ \
    [41 ] = sys_socket_impl, /* socket (common) */ \
    [42 ] = sys_connect_impl, /* connect (common) */ \
    [43 ] = sys_accept_impl, /* accept (common) */ \
    [44 ] = sys_sendto_impl, /* sendto (common) */ \
    [45 ] = sys_recvfrom_impl, /* recvfrom (common) */ \
    [46 ] = sys_sendmsg_impl, /* sendmsg (common) */ \
    [47 ] = sys_recvmsg_impl, /* recvmsg (common) */ \
    [48 ] = sys_shutdown_impl, /* shutdown (common) */ \
    [49 ] = sys_bind_impl, /* bind (common) */ \
    [50 ] = sys_listen_impl, /* listen (common) */ \
    [51 ] = sys_getsockname_impl, /* getsockname (common) */ \
    [52 ] = sys_getpeername_impl, /* getpeername (common) */ \
    [53 ] = sys_socketpair_impl, /* socketpair (common) */ \
    [54 ] = sys_setsockopt_impl, /* setsockopt (common) */ \
    [55 ] = sys_getsockopt_impl, /* getsockopt (common) */ \
    [56 ] = sys_clone_impl, /* clone (common) */ \
    [57 ] = sys_fork_impl, /* fork (common) */ \
    [58 ] = sys_vfork_impl, /* vfork (common) */ \
    [59 ] = sys_execve_impl, /* execve (common) */ \
    [60 ] = sys_exit_impl, /* exit (common) */ \
    [61 ] = sys_wait4_impl, /* wait4 (common) */ \
    [62 ] = sys_kill_impl, /* kill (common) */ \
    [63 ] = sys_uname_impl, /* uname (common) */ \
    [64 ] = sys_semget_impl, /* semget (common) */ \
    [65 ] = sys_semop_impl, /* semop (common) */ \
    [66 ] = sys_semctl_impl, /* semctl (common) */ \
    [67 ] = sys_shmdt_impl, /* shmdt (common) */ \
    [68 ] = sys_msgget_impl, /* msgget (common) */ \
    [69 ] = sys_msgsnd_impl, /* msgsnd (common) */ \
    [70 ] = sys_msgrcv_impl, /* msgrcv (common) */ \
    [71 ] = sys_msgctl_impl, /* msgctl (common) */ \
    [72 ] = sys_fcntl_impl, /* fcntl (common) */ \
    [73 ] = sys_flock_impl, /* flock (common) */ \
    [74 ] = sys_fsync_impl, /* fsync (common) */ \
    [75 ] = sys_fdatasync_impl, /* fdatasync (common) */ \
    [76 ] = sys_truncate_impl, /* truncate (common) */ \
    [77 ] = sys_ftruncate_impl, /* ftruncate (common) */ \
    [78 ] = sys_getdents_impl, /* getdents (common) */ \
    [79 ] = sys_getcwd_impl, /* getcwd (common) */ \
    [80 ] = sys_chdir_impl, /* chdir (common) */ \
    [81 ] = sys_fchdir_impl, /* fchdir (common) */ \
    [82 ] = sys_rename_impl, /* rename (common) */ \
    [83 ] = sys_mkdir_impl, /* mkdir (common) */ \
    [84 ] = sys_rmdir_impl, /* rmdir (common) */ \
    [85 ] = sys_creat_impl, /* creat (common) */ \
    [86 ] = sys_link_impl, /* link (common) */ \
    [87 ] = sys_unlink_impl, /* unlink (common) */ \
    [88 ] = sys_symlink_impl, /* symlink (common) */ \
    [89 ] = sys_readlink_impl, /* readlink (common) */ \
    [90 ] = sys_chmod_impl, /* chmod (common) */ \
    [91 ] = sys_fchmod_impl, /* fchmod (common) */ \
    [92 ] = sys_chown_impl, /* chown (common) */ \
    [93 ] = sys_fchown_impl, /* fchown (common) */ \
    [94 ] = sys_lchown_impl, /* lchown (common) */ \
    [95 ] = sys_umask_impl, /* umask (common) */ \
    [96 ] = sys_gettimeofday_impl, /* gettimeofday (common) */ \
    [97 ] = sys_getrlimit_impl, /* getrlimit (common) */ \
    [98 ] = sys_getrusage_impl, /* getrusage (common) */ \
    [99 ] = sys_sysinfo_impl, /* sysinfo (common) */ \
    [100] = sys_times_impl, /* times (common) */ \
    [101] = sys_ptrace_impl, /* ptrace (common) */ \
    [102] = sys_getuid_impl, /* getuid (common) */ \
    [103] = sys_syslog_impl, /* syslog (common) */ \
    [104] = sys_getgid_impl, /* getgid (common) */ \
    [105] = sys_setuid_impl, /* setuid (common) */ \
    [106] = sys_setgid_impl, /* setgid (common) */ \
    [107] = sys_geteuid_impl, /* geteuid (common) */ \
    [108] = sys_getegid_impl, /* getegid (common) */ \
    [109] = sys_setpgid_impl, /* setpgid (common) */ \
    [110] = sys_getppid_impl, /* getppid (common) */ \
    [111] = sys_getpgrp_impl, /* getpgrp (common) */ \
    [112] = sys_setsid_impl, /* setsid (common) */ \
    [113] = sys_setreuid_impl, /* setreuid (common) */ \
    [114] = sys_setregid_impl, /* setregid (common) */ \
    [115] = sys_getgroups_impl, /* getgroups (common) */ \
    [116] = sys_setgroups_impl, /* setgroups (common) */ \
    [117] = sys_setresuid_impl, /* setresuid (common) */ \
    [118] = sys_getresuid_impl, /* getresuid (common) */ \
    [119] = sys_setresgid_impl, /* setresgid (common) */ \
    [120] = sys_getresgid_impl, /* getresgid (common) */ \
    [121] = sys_getpgid_impl, /* getpgid (common) */ \
    [122] = sys_setfsuid_impl, /* setfsuid (common) */ \
    [123] = sys_setfsgid_impl, /* setfsgid (common) */ \
    [124] = sys_getsid_impl, /* getsid (common) */ \
    [125] = sys_capget_impl, /* capget (common) */ \
    [126] = sys_capset_impl, /* capset (common) */ \
    [127] = sys_rt_sigpending_impl, /* rt_sigpending (common) */ \
    [128] = sys_rt_sigtimedwait_impl, /* rt_sigtimedwait (common) */ \
    [129] = sys_rt_sigqueueinfo_impl, /* rt_sigqueueinfo (common) */ \
    [130] = sys_rt_sigsuspend_impl, /* rt_sigsuspend (common) */ \
    [131] = sys_sigaltstack_impl, /* sigaltstack (common) */ \
    [132] = sys_utime_impl, /* utime (common) */ \
    [133] = sys_mknod_impl, /* mknod (common) */ \
    [135] = sys_personality_impl, /* personality (common) */ \
    [137] = sys_statfs_impl, /* statfs (common) */ \
    [138] = sys_fstatfs_impl, /* fstatfs (common) */ \
    [140] = sys_getpriority_impl, /* getpriority (common) */ \
    [141] = sys_setpriority_impl, /* setpriority (common) */ \
    [142] = sys_sched_setparam_impl, /* sched_setparam (common) */ \
    [143] = sys_sched_getparam_impl, /* sched_getparam (common) */ \
    [144] = sys_sched_setscheduler_impl, /* sched_setscheduler (common) */ \
    [145] = sys_sched_getscheduler_impl, /* sched_getscheduler (common) */ \
    [146] = sys_sched_get_priority_max_impl, /* sched_get_priority_max (common) */ \
    [147] = sys_sched_get_priority_min_impl, /* sched_get_priority_min (common) */ \
    [148] = sys_sched_rr_get_interval_impl, /* sched_rr_get_interval (common) */ \
    [149] = sys_mlock_impl, /* mlock (common) */ \
    [150] = sys_munlock_impl, /* munlock (common) */ \
    [151] = sys_mlockall_impl, /* mlockall (common) */ \
    [152] = sys_munlockall_impl, /* munlockall (common) */ \
    [153] = sys_vhangup_impl, /* vhangup (common) */ \
    [155] = sys_pivot_root_impl, /* pivot_root (common) */ \
    [157] = sys_prctl_impl, /* prctl (common) */ \
    [158] = sys_arch_prctl_impl, /* arch_prctl (common) */ \
    [159] = sys_adjtimex_impl, /* adjtimex (common) */ \
    [160] = sys_setrlimit_impl, /* setrlimit (common) */ \
    [161] = sys_chroot_impl, /* chroot (common) */ \
    [162] = sys_sync_impl, /* sync (common) */ \
    [163] = sys_acct_impl, /* acct (common) */ \
    [164] = sys_settimeofday_impl, /* settimeofday (common) */ \
    [165] = sys_mount_impl, /* mount (common) */ \
    [166] = sys_umount2_impl, /* umount2 (common) */ \
    [167] = sys_swapon_impl, /* swapon (common) */ \
    [168] = sys_swapoff_impl, /* swapoff (common) */ \
    [169] = sys_reboot_impl, /* reboot (common) */ \
    [170] = sys_sethostname_impl, /* sethostname (common) */ \
    [171] = sys_setdomainname_impl, /* setdomainname (common) */ \
    [172] = sys_iopl_impl, /* iopl (common) */ \
    [173] = sys_ioperm_impl, /* ioperm (common) */ \
    [175] = sys_finit_module_impl, /* init_module (common) */ \
    [176] = sys_finit_module_impl, /* delete_module (common) */ \
    [186] = sys_gettid_impl, /* gettid (common) */ \
    [187] = sys_readahead_impl, /* readahead (common) */ \
    [188] = sys_setxattr_impl, /* setxattr (common) */ \
    [189] = sys_lsetxattr_impl, /* lsetxattr (common) */ \
    [190] = sys_fsetxattr_impl, /* fsetxattr (common) */ \
    [191] = sys_getxattr_impl, /* getxattr (common) */ \
    [192] = sys_lgetxattr_impl, /* lgetxattr (common) */ \
    [193] = sys_fgetxattr_impl, /* fgetxattr (common) */ \
    [194] = sys_listxattr_impl, /* listxattr (common) */ \
    [195] = sys_llistxattr_impl, /* llistxattr (common) */ \
    [196] = sys_flistxattr_impl, /* flistxattr (common) */ \
    [197] = sys_removexattr_impl, /* removexattr (common) */ \
    [198] = sys_lremovexattr_impl, /* lremovexattr (common) */ \
    [199] = sys_fremovexattr_impl, /* fremovexattr (common) */ \
    [200] = sys_tkill_impl, /* tkill (common) */ \
    [201] = sys_time_impl, /* time (common) */ \
    [202] = sys_futex_impl, /* futex (common) */ \
    [203] = sys_sched_setaffinity_impl, /* sched_setaffinity (common) */ \
    [204] = sys_sched_getaffinity_impl, /* sched_getaffinity (common) */ \
    [206] = sys_io_setup_impl, /* io_setup (common) */ \
    [207] = sys_io_destroy_impl, /* io_destroy (common) */ \
    [208] = sys_io_getevents_impl, /* io_getevents (common) */ \
    [209] = sys_io_submit_impl, /* io_submit (common) */ \
    [210] = sys_io_cancel_impl, /* io_cancel (common) */ \
    [213] = sys_epoll_create_impl, /* epoll_create (common) */ \
    [217] = sys_getdents64_impl, /* getdents64 (common) */ \
    [218] = sys_set_tid_address_impl, /* set_tid_address (common) */ \
    [219] = sys_restart_syscall_impl, /* restart_syscall (common) */ \
    [220] = sys_semtimedop_impl, /* semtimedop (common) */ \
    [221] = sys_fadvise64_impl, /* fadvise64 (common) */ \
    [222] = sys_timer_create_impl, /* timer_create (common) */ \
    [223] = sys_timer_settime_impl, /* timer_settime (common) */ \
    [224] = sys_timer_gettime_impl, /* timer_gettime (common) */ \
    [225] = sys_timer_getoverrun_impl, /* timer_getoverrun (common) */ \
    [226] = sys_timer_delete_impl, /* timer_delete (common) */ \
    [227] = sys_clock_settime_impl, /* clock_settime (common) */ \
    [228] = sys_clock_gettime_impl, /* clock_gettime (common) */ \
    [229] = sys_clock_getres_impl, /* clock_getres (common) */ \
    [230] = sys_clock_nanosleep_impl, /* clock_nanosleep (common) */ \
    [231] = sys_exit_group_impl, /* exit_group (common) */ \
    [232] = sys_epoll_wait_impl, /* epoll_wait (common) */ \
    [233] = sys_epoll_ctl_impl, /* epoll_ctl (common) */ \
    [234] = sys_tgkill_impl, /* tgkill (common) */ \
    [235] = sys_utimes_impl, /* utimes (common) */ \
    [237] = sys_mbind_impl, /* mbind (common) */ \
    [238] = sys_set_mempolicy_impl, /* set_mempolicy (common) */ \
    [239] = sys_get_mempolicy_impl, /* get_mempolicy (common) */ \
    [240] = sys_mq_open_impl, /* mq_open (common) */ \
    [241] = sys_mq_unlink_impl, /* mq_unlink (common) */ \
    [242] = sys_mq_timedsend_impl, /* mq_timedsend (common) */ \
    [243] = sys_mq_timedreceive_impl, /* mq_timedreceive (common) */ \
    [244] = sys_mq_notify_impl, /* mq_notify (common) */ \
    [245] = sys_mq_getsetattr_impl, /* mq_getsetattr (common) */ \
    [247] = sys_waitid_impl, /* waitid (common) */ \
    [248] = sys_add_key_impl, /* add_key (common) */ \
    [249] = sys_request_key_impl, /* request_key (common) */ \
    [250] = sys_keyctl_impl, /* keyctl (common) */ \
    [251] = sys_ioprio_set_impl, /* ioprio_set (common) */ \
    [252] = sys_ioprio_get_impl, /* ioprio_get (common) */ \
    [253] = sys_inotify_init_impl, /* inotify_init (common) */ \
    [254] = sys_inotify_add_watch_impl, /* inotify_add_watch (common) */ \
    [255] = sys_inotify_rm_watch_impl, /* inotify_rm_watch (common) */ \
    [256] = sys_migrate_pages_impl, /* migrate_pages (common) */ \
    [257] = sys_openat_impl, /* openat (common) */ \
    [258] = sys_mkdirat_impl, /* mkdirat (common) */ \
    [259] = sys_mknodat_impl, /* mknodat (common) */ \
    [260] = sys_fchownat_impl, /* fchownat (common) */ \
    [261] = sys_futimesat_impl, /* futimesat (common) */ \
    [262] = sys_fstatat_impl, /* fstatat (common) */ \
    [263] = sys_unlinkat_impl, /* unlinkat (common) */ \
    [264] = sys_renameat_impl, /* renameat (common) */ \
    [265] = sys_linkat_impl, /* linkat (common) */ \
    [266] = sys_symlinkat_impl, /* symlinkat (common) */ \
    [267] = sys_readlinkat_impl, /* readlinkat (common) */ \
    [268] = sys_fchmodat_impl, /* fchmodat (common) */ \
    [269] = sys_faccessat_impl, /* faccessat (common) */ \
    [270] = sys_pselect6_impl, /* pselect6 (common) */ \
    [271] = sys_ppoll_impl, /* ppoll (common) */ \
    [272] = sys_unshare_impl, /* unshare (common) */ \
    [273] = sys_set_robust_list_impl, /* set_robust_list (common) */ \
    [274] = sys_get_robust_list_impl, /* get_robust_list (common) */ \
    [275] = sys_splice_impl, /* splice (common) */ \
    [276] = sys_tee_impl, /* tee (common) */ \
    [277] = sys_sync_file_range_impl, /* sync_file_range (common) */ \
    [278] = sys_vmsplice_impl, /* vmsplice (common) */ \
    [279] = sys_move_pages_impl, /* move_pages (common) */ \
    [280] = sys_utimensat_impl, /* utimensat (common) */ \
    [281] = sys_epoll_pwait_impl, /* epoll_pwait (common) */ \
    [282] = sys_signalfd_impl, /* signalfd (common) */ \
    [283] = sys_timerfd_create_impl, /* timerfd_create (common) */ \
    [284] = sys_eventfd_impl, /* eventfd (common) */ \
    [285] = sys_fallocate_impl, /* fallocate (common) */ \
    [286] = sys_timerfd_settime_impl, /* timerfd_settime (common) */ \
    [287] = sys_timerfd_gettime_impl, /* timerfd_gettime (common) */ \
    [288] = sys_accept4_impl, /* accept4 (common) */ \
    [289] = sys_signalfd4_impl, /* signalfd4 (common) */ \
    [290] = sys_eventfd2_impl, /* eventfd2 (common) */ \
    [291] = sys_epoll_create1_impl, /* epoll_create1 (common) */ \
    [292] = sys_dup3_impl, /* dup3 (common) */ \
    [293] = sys_pipe2_impl, /* pipe2 (common) */ \
    [294] = sys_inotify_init1_impl, /* inotify_init1 (common) */ \
    [295] = sys_preadv_impl, /* preadv (common) */ \
    [296] = sys_pwritev_impl, /* pwritev (common) */ \
    [297] = sys_rt_tgsigqueueinfo_impl, /* rt_tgsigqueueinfo (common) */ \
    [298] = sys_perf_event_open_impl, /* perf_event_open (common) */ \
    [299] = sys_recvmmsg_impl, /* recvmmsg (common) */ \
    [300] = sys_fanotify_init_impl, /* fanotify_init (common) */ \
    [301] = sys_fanotify_mark_impl, /* fanotify_mark (common) */ \
    [302] = sys_prlimit64_impl, /* prlimit64 (common) */ \
    [303] = sys_name_to_handle_at_impl, /* name_to_handle_at (common) */ \
    [304] = sys_open_by_handle_at_impl, /* open_by_handle_at (common) */ \
    [305] = sys_clock_adjtime_impl, /* clock_adjtime (common) */ \
    [306] = sys_syncfs_impl, /* syncfs (common) */ \
    [307] = sys_sendmmsg_impl, /* sendmmsg (common) */ \
    [308] = sys_setns_impl, /* setns (common) */ \
    [309] = sys_getcpu_impl, /* getcpu (common) */ \
    [310] = sys_process_vm_readv_impl, /* process_vm_readv (common) */ \
    [311] = sys_process_vm_writev_impl, /* process_vm_writev (common) */ \
    [312] = sys_kcmp_impl, /* kcmp (common) */ \
    [313] = sys_finit_module_impl, /* finit_module (common) */ \
    [314] = sys_sched_setattr_impl, /* sched_setattr (common) */ \
    [315] = sys_sched_getattr_impl, /* sched_getattr (common) */ \
    [316] = sys_renameat2_impl, /* renameat2 (common) */ \
    [317] = sys_seccomp_impl, /* seccomp (common) */ \
    [318] = sys_getrandom_impl, /* getrandom (common) */ \
    [319] = sys_memfd_create_impl, /* memfd_create (common) */ \
    [320] = sys_kexec_file_load_impl, /* kexec_file_load (common) */ \
    [321] = sys_bpf_impl, /* bpf (common) */ \
    [322] = sys_execveat_impl, /* execveat (common) */ \
    [323] = sys_userfaultfd_impl, /* userfaultfd (common) */ \
    [324] = sys_membarrier_impl, /* membarrier (common) */ \
    [325] = sys_mlock2_impl, /* mlock2 (common) */ \
    [326] = sys_copy_file_range_impl, /* copy_file_range (common) */ \
    [327] = sys_preadv_impl, /* preadv2 (common) */ \
    [328] = sys_pwritev_impl, /* pwritev2 (common) */ \
    [329] = sys_pkey_mprotect_impl, /* pkey_mprotect (common) */ \
    [330] = sys_pkey_alloc_impl, /* pkey_alloc (common) */ \
    [331] = sys_pkey_free_impl, /* pkey_free (common) */ \
    [332] = sys_statx_impl, /* statx (common) */ \
    [333] = sys_io_pgetevents_impl, /* io_pgetevents (common) */ \
    [334] = sys_rseq_impl, /* rseq (common) */ \
    [424] = sys_pidfd_send_signal_impl, /* pidfd_send_signal (common) */ \
    [425] = sys_io_uring_setup_impl, /* io_uring_setup (common) */ \
    [426] = sys_io_uring_enter_impl, /* io_uring_enter (common) */ \
    [427] = sys_io_uring_register_impl, /* io_uring_register (common) */ \
    [428] = sys_open_tree_impl, /* open_tree (common) */ \
    [429] = sys_move_mount_impl, /* move_mount (common) */ \
    [430] = sys_fsopen_impl, /* fsopen (common) */ \
    [431] = sys_fsconfig_impl, /* fsconfig (common) */ \
    [432] = sys_fsmount_impl, /* fsmount (common) */ \
    [433] = sys_fspick_impl, /* fspick (common) */ \
    [434] = sys_pidfd_open_impl, /* pidfd_open (common) */ \
    [435] = sys_clone3_impl, /* clone3 (common) */ \
    [436] = sys_close_range_impl, /* close_range (common) */ \
    [437] = sys_openat2_impl, /* openat2 (common) */ \
    [438] = sys_pidfd_getfd_impl, /* pidfd_getfd (common) */ \
    [439] = sys_faccessat2_impl, /* faccessat2 (common) */ \
    [440] = sys_process_madvise_impl, /* process_madvise (common) */ \
    [441] = sys_epoll_pwait2_impl, /* epoll_pwait2 (common) */ \
    [442] = sys_mount_setattr_impl, /* mount_setattr (common) */ \
    [443] = sys_quotactl_fd_impl, /* quotactl_fd (common) */ \
    [444] = sys_landlock_create_ruleset_impl, /* landlock_create_ruleset (common) */ \
    [445] = sys_landlock_add_rule_impl, /* landlock_add_rule (common) */ \
    [446] = sys_landlock_restrict_self_impl, /* landlock_restrict_self (common) */ \
    [447] = sys_memfd_secret_impl, /* memfd_secret (common) */ \
    [448] = sys_process_mrelease_impl, /* process_mrelease (common) */ \
    [449] = sys_futex_waitv_impl, /* futex_waitv (common) */ \
    [450] = sys_set_mempolicy_home_node_impl, /* set_mempolicy_home_node (common) */ \
    [451] = sys_cachestat_impl, /* cachestat (common) */ \
    [452] = sys_fchmodat2_impl, /* fchmodat2 (common) */ \
    [453] = sys_map_shadow_stack_impl, /* map_shadow_stack (common) */ \
    [454] = sys_futex_wake_impl, /* futex_wake (common) */ \
    [455] = sys_futex_wait_impl, /* futex_wait (common) */ \
    [456] = sys_futex_requeue_impl, /* futex_requeue (common) */ \
    [457] = sys_statmount_impl, /* statmount (common) */ \
    [458] = sys_listmount_impl, /* listmount (common) */ \
    [459] = sys_lsm_get_self_attr_impl, /* lsm_get_self_attr (common) */ \
    [460] = sys_lsm_set_self_attr_impl, /* lsm_set_self_attr (common) */ \
    [461] = sys_lsm_list_modules_impl, /* lsm_list_modules (common) */ \
    [462] = sys_mseal_impl, /* mseal (common) */ \
    [512] = sys_az_channel_create, /* AZ_CHANNEL_CREATE (common) */ \
    [513] = sys_az_channel_send, /* AZ_CHANNEL_SEND (common) */ \
    [514] = sys_az_channel_recv, /* AZ_CHANNEL_RECV (common) */ \
    [515] = sys_az_shmem_create, /* AZ_SHMEM_CREATE (common) */ \
    [516] = sys_az_shmem_map, /* AZ_SHMEM_MAP (common) */ \
    [517] = sys_az_object_create, /* AZ_OBJECT_CREATE (common) */ \
    [518] = sys_az_object_open, /* AZ_OBJECT_OPEN (common) */ \
    [519] = sys_az_object_close, /* AZ_OBJECT_CLOSE (common) */ \
    [520] = sys_az_fb_info, /* AZ_FB_INFO (common) */ \
    [521] = sys_az_fb_map, /* AZ_FB_MAP (common) */ \
    [522] = sys_az_spawn, /* AZ_SPAWN (common) */ \
    [523] = sys_az_yield, /* AZ_YIELD (common) */ \
    [524] = sys_az_thread_create_impl, /* AZ_THREAD_CREATE (common) */ \
    [525] = sys_az_sysstat_impl, /* AZ_SYSSTAT (common) */ \
    [526] = sys_az_shmem_destroy, /* AZ_SHMEM_DESTROY (common) */ \
    [527] = sys_az_shmem_unmap, /* AZ_SHMEM_UNMAP (common) */ \
    [528] = sys_az_channel_destroy, /* AZ_CHANNEL_DESTROY (common) */ \
    [529] = sys_az_set_timer_impl, /* AZ_SET_TIMER (common) */ \
    [530] = sys_az_thread_exit_impl, /* AZ_THREAD_EXIT (common) */ \
    [531] = sys_az_fb_flip, /* AZ_FB_FLIP (common) */ \
    [532] = sys_getfacl_impl, /* AZ_GETFACL (common) */ \
    [533] = sys_setfacl_impl, /* AZ_SETFACL (common) */ \
    [534] = sys_az_sem_open_impl, /* AZ_SEM_OPEN (common) */ \
    [535] = sys_az_sem_close_impl, /* AZ_SEM_CLOSE (common) */ \
    [536] = sys_az_sem_post_impl, /* AZ_SEM_POST (common) */ \
    [537] = sys_az_sem_wait_impl, /* AZ_SEM_WAIT (common) */ \
    [538] = sys_az_sem_trywait_impl, /* AZ_SEM_TRYWAIT (common) */ \
    [539] = sys_az_sem_timedwait_impl, /* AZ_SEM_TIMEDWAIT (common) */ \
    [540] = sys_az_sem_unlink_impl, /* AZ_SEM_UNLINK (common) */ \
    [541] = sys_az_sem_getvalue_impl, /* AZ_SEM_GETVALUE (common) */ \
    [542] = sys_az_ktrace_enable_impl, /* AZ_KTRACE_ENABLE (common) */ \
    [543] = sys_az_ktrace_read_impl, /* AZ_KTRACE_READ (common) */ \
    [544] = sys_az_ktrace_clear_impl, /* AZ_KTRACE_CLEAR (common) */ \
    [545] = sys_az_spawn_arg, /* AZ_SPAWN_ARG (common) */ \
}

